/**
 * The four legal documents, transcribed from the Markdown files the user
 * supplied on 2026-09-29 (TEX-Terms of Website Use & Conditions, TEX-Legal
 * Notices and Disclaimer, TEX-Cookies Policy, TEX-Privacy Policy). The wording
 * is theirs and is kept verbatim; only the Markdown was turned into blocks.
 * Do not edit the text here without a new version of the source document.
 */

export type LegalBlock =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "h4"; text: string }
  /** A bold lead-in sentence that introduces the list after it. */
  | { type: "strong"; text: string }
  | { type: "p"; text: string; lead?: string }
  | { type: "ul"; items: string[] }
  | { type: "address"; label?: string; lines: string[] }
  /** Two columns: a name and a link. */
  | { type: "links"; rows: [string, string][] };

export type LegalDocument = {
  slug: "terms" | "legal" | "cookies" | "privacy";
  href: string;
  title: string;
  /** As stated in the document, where it states one. */
  updated?: string;
  blocks: LegalBlock[];
};

export const headingId = (text: string) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export const PRIVACY: LegalDocument = {
  slug: "privacy",
  href: "/privacy",
  title: "Privacy Policy & Protection of Personal Data",
  updated: "11 May 2022",
  blocks: [
    { type: "h2", text: "1. Purpose" },
    { type: "p", text: "Law on the Protection of Personal Data in Turkey (KVKK Law in short) was published in the Official Gazette dated 7 April 2016. The purpose of this law is to protect the fundamental rights and freedoms of individuals, the privacy of private life, and to impose obligations against any wrongful act in Turkey." },
    { type: "p", text: "We aim to establish a data security and storage policy with the Personal Data Protection Law. We protect and preserve your personal data with this policy." },
    { type: "h2", text: "2. Scope" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is a registered brand. We are an overseas real estate company based in Turkey. tekceexclusive.com is owned and run by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "p", text: "The scope of this policy covers the Tekce Exclusive Gayrimenkul Pazarlama AŞ team and tekceexclusive.com visitors. The policy is used in all activities created and carried out by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "p", text: "This policy has been prepared in accordance with the KVKK Law and must be accepted by our all employees. Tekce Exclusive Gayrimenkul Pazarlama AŞ expects that all customers, visitors, and employees comply with this policy. The company provides necessary information about this policy and provides relevant materials to the employees." },
    { type: "h2", text: "3. Glossary of Terms" },
    { type: "h3", text: "3.1. Tekce Exclusive Gayrimenkul Pazarlama AŞ" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is an overseas real estate company." },
    { type: "h3", text: "3.2. Explicit Consent" },
    { type: "p", text: "Limited permission is given for the processing of data. It is based on free will and is presented for informational purposes only." },
    { type: "h3", text: "3.3. Anonymization" },
    { type: "p", text: "It is the rendering of personal data that cannot be associated with an identified or identifiable person, even if it is matched with other data." },
    { type: "h3", text: "3.4. Employees" },
    { type: "p", text: "The team of Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "h3", text: "3.5. Service Provider" },
    { type: "p", text: "Employees of the third-party company that Tekce Exclusive Gayrimenkul Pazarlama AŞ receives service from." },
    { type: "h3", text: "3.6. Individual / Customer / Visitor" },
    { type: "p", text: "The person whose personal information is kept and processed by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "h3", text: "3.7. Personal Information / Personal Data" },
    { type: "p", text: "Information about contacts/customers/visitors allows them to be identified, such as e-mail address and phone number." },
    { type: "h3", text: "3.8. Processing of Personal Data" },
    { type: "p", text: "Automatically collecting, changing, storing, saving, editing, or disclosing personal information, in whole or in part." },
    { type: "h3", text: "3.9. Data Controller" },
    { type: "p", text: "Persons who decide what personal information Tekce Exclusive Gayrimenkul Pazarlama AŞ will hold and how it will be held and used." },
    { type: "h3", text: "3.10. Data Processor" },
    { type: "p", text: "Natural or legal persons who process data under the authority of the Data Controller." },
    { type: "h3", text: "3.11. KVKK Board" },
    { type: "p", text: "The Board of Protection of Personal Data. (Kişisel Verilerin Korunması Kanunu (KVKK) in Turkish)" },
    { type: "h3", text: "3.12. KVKK Corporation" },
    { type: "p", text: "The Corporation for the Protection of Personal Data." },
    { type: "h3", text: "3.13. Law of KVKK" },
    { type: "p", text: "The Turkish Personal Data Protection Law was published in the Official Gazette numbered 29677." },
    { type: "h3", text: "3.14. Policy" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ’s Personal Data Protection and Processing Policy." },
    { type: "h2", text: "4. Roles and Responsibilities" },
    { type: "h3", text: "4.1. Data Controller" },
    { type: "p", text: "The processing of Personal Data refers to the automatically collecting, amending, storing, saving, editing, or disclosing of personal data, in whole or in part, within the framework of the provisions of the Turkish Personal Data Protection Law." },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ needs to collect and use certain types of information about visitors or customers to continue our work. Tekce Exclusive Gayrimenkul Pazarlama AŞ is the Data Controller within the scope of the Law and determines the purpose for which the data will be used." },
    { type: "h3", text: "4.2. Data Controller Agent" },
    { type: "p", text: "A Data Controller Agent will be needed when the Data Controllers Registry is established. This agent should be an expert in keeping data confidential, processing, and taking the necessary security steps." },
    { type: "h3", text: "4.3. Data Processor" },
    { type: "p", text: "Data processors are natural or legal persons who process Personal Data. The processor must be operating under the authority of Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "h3", text: "4.4. Responsibilities" },
    { type: "p", text: "If the data is processed by natural or legal persons, Tekce Exclusive Gayrimenkul Pazarlama AŞ and Data Processors are obliged to take precautions. As Data Controllers, Tekce Exclusive Gayrimenkul Pazarlama AŞ supervises the trust process between the two parties; Tekce Exclusive Gayrimenkul Pazarlama AŞ and individuals." },
    { type: "h2", text: "5. Legal Obligations" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ has legal obligations regarding the security and processing of Personal Data in accordance with the KVKK Law. These are:" },
    { type: "h3", text: "5.1. The Obligation to Clarify" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to inform the visitors and customers about the following issues during Data Processing:" },
    {
      type: "ul",
      items: [
        "The identity of the Data Controller",
        "Reasons for keeping Personal Data",
        "Legal reasons for keeping Personal Data",
        "Rights of persons",
      ],
    },
    { type: "h3", text: "5.2. The Obligation to Inform" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to inform the visitors and customers in accordance with Article 13 of the KVKK Law. In addition, information requests must be fulfilled via info@tekceexclusive.com or 0850 811 07 00." },
    { type: "p", text: "The special requests must be written by persons manually or by any other methods to be determined by the KVKK Board." },
    { type: "h3", text: "5.3. The Obligation to Provide Personal Data Security" },
    { type: "p", text: "As Data Controllers, Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to provide the necessary security services in accordance with Article 12 of the KVKK Law." },
    { type: "h3", text: "5.4. The Obligation to Enlist in the Data Controllers Registry" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to register with the Data Controllers Registry in accordance with Article 16 of the KVKK Law." },
    { type: "h2", text: "6. Classification of Personal Data" },
    { type: "h3", text: "6.1. Personal Data" },
    { type: "p", text: "Information considered as Personal Data is an individual’s name, surname, date and place of birth, identity, social security number, telephone number, e-mail address, address, image, payment information, and other such information." },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ keeps some of this data, such as name, surname, telephone number, and e-mail address, due to membership conditions." },
    { type: "h3", text: "6.2. Private Personal Data" },
    { type: "p", text: "Information considered as Private Personal Data is an individual’s race, ethnicity, political opinion, philosophical belief, religion, sect or other beliefs, rig, membership to any foundation or organization, health problems, sexual life, convictions, security measures, biometric and genetic data." },
    { type: "p", text: "It is strictly forbidden to keep such data without the consent of individuals in accordance with Article 6 of the Turkish KVKK Law. As Data Controllers, Tekce Exclusive Gayrimenkul Pazarlama AŞ never request such Private Personal Data unless it is specified by laws." },
    { type: "h2", text: "7. The Policy of Personal Data Processing" },
    { type: "h3", text: "7.1. The Principles for Data Processing" },
    { type: "p", text: "All collected data must be processed in accordance with Articles 4, 5, and 6 of the KVKK Law." },
    {
      type: "ul",
      items: [
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ must process the data in accordance with the KVKK Law and other legal regulations.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ must be transparent, fulfill the obligations to clarify and inform by adhering to the rules of honesty.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ should only process the data for justifiable reasons. The reasons must be lawful and specified in the KVKK Law or other legal regulations.",
        "The data must be relevant to the purpose and limited to that purpose only.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ must process data at the required scale. The code of proportion must be enforced and only the necessary bit of the data must be processed.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ must keep data only for as long as needed (see section 9) and must not keep data if the required time has passed anonymously.",
      ],
    },
    { type: "h3", text: "7.2. The Objectives of Data Processing" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ does not collect and save any personal information from any customer in order to send unwanted and unsolicited information (spam). We aim to process data for some purposes such as:" },
    {
      type: "ul",
      items: [
        "Personal and contact data, such as name, surname, phone number, e-mail address, are processed for website registration and higher quality communication.",
        "Demographic site or app browsing data is processed to analyze and collect user points of interest. This data is used to improve business and operational activities, such as remarketing, retargeting, and communications.",
        "Social web information is used to provide a better and easier experience on the website. Some social websites, such as Facebook, Twitter, Linkedin, can only be used to register on the Tekce Exclusive Gayrimenkul Pazarlama AŞ website.",
        "Location data is used if the user gives permission from mobile phones while browsing. We process location data to suggest properties and show the closest offices by location.",
      ],
    },
    { type: "p", text: "The data is processed for other purposes in addition to the above-mentioned purposes;" },
    {
      type: "ul",
      items: [
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ sends properties and hot offers via e-mail addresses in a newsletter format.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ deals with each customer individually by answering any questions and needs provided by the contact data.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ informs about new services.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ engages in direct marketing.",
        "Tekce Exclusive Gayrimenkul Pazarlama AŞ can communicate directly with people when necessary.",
      ],
    },
    { type: "h3", text: "7.3. Ensuring the Data to be Processed on Legal Grounds" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ takes the following technical precautions for the processing of personal data on legal grounds:" },
    {
      type: "ul",
      items: [
        "Arranging an intercorporate institution for the processing and storage of Personal Data in accordance with the Law",
        "Establishing the technical infrastructure for the database where all Personal Data will be kept",
        "Supervising the created technical infrastructure and process",
        "Designating the necessary procedures for reporting technical procedures and inspection periods",
      ],
    },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ takes the following legal precautions for the processing of personal data on legal grounds:" },
    {
      type: "ul",
      items: [
        "To educate and inform Tekce Exclusive Gayrimenkul Pazarlama AŞ employees about the legal processing of personal data",
        "To take precautions against any unlawful processing of personal data in contracts, legal files, and policies",
        "To inspect the personal data processing of third-party processors and partners",
      ],
    },
    { type: "h2", text: "8. The Policy of Transferring the Personal Data" },
    { type: "h3", text: "8.1. Transferring the Personal Data Inland" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to act in accordance with the KVKK Law and the regulations determined by the KVKK Board. As Data Controllers, Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to comply with the KVKK Law." },
    { type: "p", text: "We never share any personal data or information with third-party companies without the consent of the person. However, in case of obligations arising from the KVKK Law and other Constitutional Laws, we may transfer the data to the relevant jurisdiction, governmental or legal bodies." },
    { type: "h3", text: "8.2. Transferring the Personal Data Abroad" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ can also transfer data abroad for processing and storage. The country that will receive the Personal Data must have taken the necessary security measures. The measures should be controlled by the KVKK Board." },
    { type: "p", text: "In case the necessary measures are not sufficient, Data Controllers from both Turkey and the recipient country must make a written commitment, and the KVKK Board must approve it." },
    { type: "h3", text: "8.3. Which Person/Organization Receives the Personal Data?" },
    { type: "p", text: "Authorized institutions and organizations: Public legal entities can receive the Data as they request, according to Article 8.1. Tekce Exclusive Gayrimenkul Pazarlama AŞ customer program, TEKÇE, receives and stores Personal Data and keeps track of customers." },
    { type: "p", text: "Some third-party software and tools, such as Bing, Google AdWords, Google Analytics, Yandex Metrica, Yandex Direct, Whatsapp, Facebook, Twitter, Instagram, and JivoChat, collect Personal Data from cookies to facilitate your browsing experience." },
    { type: "h3", text: "8.4. The Precautions for Transferring the Personal Data" },
    { type: "h4", text: "Technical Precautions" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to take the necessary technical measures in case of unauthorized access to and use of Personal Data by any data processor person or company, even if these data processors are authorized by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "h4", text: "Executive Precautions" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ has established internal policies on how and for what purpose the data should be transferred. We also determine the parties to whom the data should be transferred." },
    { type: "h2", text: "9. The Policy of the Personal Data Preservation" },
    { type: "h3", text: "9.1. Preserving the Data for a Specific Amount of Time" },
    { type: "p", text: "According to the KVKK Law, any information related to persons known or found is personal data. All information, such as e-mail addresses and phone numbers, are securely saved and stored by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "p", text: "In this context, Tekce Exclusive Gayrimenkul Pazarlama AŞ is obliged to act in accordance with the law while obtaining and storing the data. The data will be stored until the preservation purpose (see 7.2) is finished. According to government obligations, data must be kept for an average of 2 years." },
    { type: "p", text: "This period changed from law to law. For example, according to the Tax Procedure Law, registration and credentials must be kept for 5 years." },
    { type: "h3", text: "9.2. The Precautions for Processing the Personal Data" },
    { type: "h4", text: "Technical Precautions" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ takes measures to ensure the safety and security of personal data. The needed systems and control mechanisms as technical measures are established." },
    { type: "h4", text: "Executive Precautions" },
    { type: "p", text: "We also create awareness and education among our employees on the protection of Personal Data. We are obliged to examine these measures for the protection of personal data." },
    { type: "h2", text: "10. Safety Policy of the Personal Data" },
    { type: "h3", text: "10.1. Responsibilities of Tekce Exclusive Gayrimenkul Pazarlama AŞ about the Safety of Data" },
    { type: "p", text: "We have the responsibility to keep Personal Data safe in accordance with Article 12 of the Personal Data Protection Law. We are responsible for:" },
    {
      type: "ul",
      items: [
        "Preventing the processing of Personal Data in violation of any law,",
        "Checking the measures regularly,",
        "Providing adequate technical equipment to stop any infiltration of Personal Data,",
        "Informing the authorized institutions in case of any infiltration.",
      ],
    },
    { type: "h3", text: "10.2. Precautions for Keeping the Personal Data Safe" },
    { type: "p", text: "We take the necessary precautions at times of security risk in order to keep Personal Data safe and secure. These precautions are as follows;" },
    { type: "h4", text: "Technical and Executive Precautions" },
    { type: "p", text: "Technical and executive measures regarding the processing, transfer, and security of Personal Data are specified in the relevant articles. We are obliged by the Law to take measures for the protection of individuals in the event that Personal Data is still leaked and in the hands of third parties unlawfully." },
    { type: "h4", text: "Precautions and Inspection for Safety of the Personal Data" },
    { type: "p", text: "We prepare a report on the compliance of the Data recorder with the KVKK Law. The recorder is periodically inspected, and the report is submitted to the authorized person or board." },
    { type: "h4", text: "Precautions in Case of Disclosure without Authorization" },
    { type: "p", text: "We are obliged to hinder all disclosure activities, take the necessary precautions, and establish an internal policy. In case of any unauthorized disclosure, we are obliged to inform the disclosed person and the KVKK Board." },
    { type: "h2", text: "11. The Rights of Individuals" },
    { type: "h3", text: "11.1. Right to Access Own Personal Data" },
    { type: "p", text: "Individuals, customers, and visitors have the right to access their personal data without making any payment. They can:" },
    {
      type: "ul",
      items: [
        "Learn whether their Personal Data is processed or not,",
        "Request information about the operation if the data is processed,",
        "Question the purpose of processing and learn whether the data is used in accordance with its purpose.",
      ],
    },
    { type: "h3", text: "11.2. Right to Change or Delete Own Personal Data" },
    { type: "p", text: "Individuals, customers, and visitors can change or delete their personal data without any payment. They can:" },
    {
      type: "ul",
      items: [
        "Request the correction of the Data in case of any wrong or incomplete information,",
        "Request the deletion of the Data if the purpose of storing the data is no longer active,",
        "Request notification of these procedures to third-party processors,",
        "Object to any negative results resulting from the analysis of the processed data by automatic systems.",
      ],
    },
    { type: "h3", text: "11.3. Updating Own Personal Data" },
    { type: "p", text: "You may contact us when you have a request to access, change, or delete your own Personal Data;" },
    { type: "p", lead: "Phone:", text: "0850 811 07 00" },
    { type: "p", lead: "E-mail:", text: "info@tekceexclusive.com" },
    { type: "p", lead: "Personal meeting or letter:", text: "Merdivenköy Mah. Nur Sok. Business Istanbul A Blok, No:1/A/410, 34732, Göztepe, Kadıköy, İstanbul, Türkiye" },
    { type: "h3", text: "11.4. Application of Individuals and Evaluation" },
    { type: "p", text: "Individuals may request access to their processed data and the use of their rights specified in this policy. Tekce Exclusive Gayrimenkul Pazarlama AŞ creates these communication opportunities. All applications are answered in a short time, not more than the KVKK Law foresees." },
    { type: "p", text: "These persons should consult the representatives who are clarified by Tekce Exclusive Gayrimenkul Pazarlama AŞ and declared by the Data Controllers Registry. The Data Controller Representative will conclude these applications in a short time and not more than 30 days, without any fee or payment determined by the KVKK Board." },
    { type: "p", text: "In order to initiate this process, individuals must send their applications to the Data Controller Representative as determined by the KVKK Board. Applications must be written in letters until the Board determines another method. The person must express their application clearly and send their official letter as a registered and reply-paid letter to:" },
    {
      type: "address",
      lines: [
        "Business İstanbul Plaza Merdivenköy Mah. Yumurtacı Abdibey Cd., Dikyol Sk. No:2/A B Blok Kat:2 Ofis: B/19 Kadıköy, İstanbul",
      ],
    },
    { type: "p", text: "The application is accepted or rejected by the Data Controller Representatives and answered in writing or electronically. If the application is accepted, the request will be made by Tekce Exclusive Gayrimenkul Pazarlama AŞ. If the fault belongs to Tekce Exclusive Gayrimenkul Pazarlama AŞ, the payment is refunded to the person." },
    { type: "p", text: "In case the application is rejected, the answer is not sufficient, or the answer is not given within the given time, the person can write a complaint letter within 30 days as it is answered within 60 days." },
    { type: "h2", text: "12. Cookie Policy" },
    { type: "p", text: "Cookie Policy is valid for mobile/websites and applications run by Tekce Exclusive Gayrimenkul Pazarlama AŞ. We use Cookies to enrich the experience of our visitors and to provide them with a better web and mobile service." },
    { type: "p", text: "Visitors can always block Cookies from their browser settings. However, blocking or limiting Cookies may affect the smooth experience visitors have. Visitors are considered to accept Cookies as long as they do not block or limit Cookies." },
    { type: "h2", text: "13. Publishing and Preserving the Policy" },
    { type: "p", text: "The most current version of the Privacy Policy will govern the collection, use, and disclosure of information about you and will be available here." },
    { type: "p", text: "If we make material changes to the Data and Privacy Policy, we will notify you prior to the effective date of the changes by email or by posting a notice on the Service. By continuing to access or use the service after the changes become effective, you accept the revised Privacy Policy." },
    { type: "h2", text: "14. The Period of Updating the Policy" },
    { type: "p", text: "We may update the Privacy Policy to reflect changes in our information practices. If we make any changes, we will notify you on our website and inform you by email (sent to the email address specified in your account). Changes will be valid after the date of the last update." },
    { type: "h2", text: "15. Validness" },
    { type: "p", text: "This policy will be valid from the moment of its publication until it is removed from the mobile app or website." },
    { type: "h2", text: "16. Security" },
    { type: "p", text: "We have taken technical and organizational security measures to prevent accidental loss, use or unauthorized access, change, or disclosure of your personal data. However, no method of transmission or electronic storage via the Internet or mobile device is 100% secure." },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ expressly disclaims any such liability and obligation." },
    { type: "h2", text: "17. International Data Transfer" },
    { type: "p", text: "For residents of the EEA or Switzerland, please note that personal data information we obtain from or about you may be transferred, processed, and stored outside of the EEA or Switzerland for the purposes described in this Privacy Policy, including in the United States of America." },
    { type: "p", text: "We take our users’ privacy seriously. Therefore, we take steps to protect your information, including ensuring an adequate level of data protection in line with EU standards." },
    { type: "p", text: "These include the application of the European Commission’s Standard Contractual Clauses for transfers of personal information between our group companies, which require all group companies to protect the personal information they process from the EEA in accordance with European Union data protection laws." },
    { type: "p", text: "We have implemented similar appropriate measures with our third-party service providers and partners, and more details can be provided on request." },
  ],
};

export const COOKIES: LegalDocument = {
  slug: "cookies",
  href: "/cookies",
  title: "Cookies Policy",
  updated: "11 May 2022",
  blocks: [
    { type: "h2", text: "The Policy of Cookie Usage" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is a registered brand, which is an overseas real estate company. tekceexclusive.com is owned by Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "p", text: "tekceexclusive.com uses cookies to enrich our users’ experiences and provide better customer service to our visitors. Our visitors can block the Use of Cookies from their browser settings and delete the data of the previous session. However, blocking the use of Cookies may affect the experience of visitors to our website." },
    { type: "p", text: "Visitors who do not block tekceexclusive.com’s Use of Cookies are deemed to have accepted Cookies." },
    { type: "h2", text: "What are Cookies?" },
    { type: "p", text: "Cookies are small text files containing a small amount of data. These files are installed on your device (or web host) while browsing a website, mobile page, or by that website when you install a mobile app through your browser or app." },
    { type: "h2", text: "There are 6 Different Types of Cookies We Use for a Better Service;" },
    { type: "h3", text: "1. Session Cookies" },
    { type: "p", text: "Session Cookies are temporary cookies that exist only in the temporary memory of the device or browser. These are activated when the visitor browses the website, mobile page, or app." },
    { type: "p", text: "The main purpose of Session Cookies is to ensure that the relevant functions of the website, mobile page, and app work perfectly by remembering the preferences of the visitors." },
    { type: "p", text: "When you add a property to your “My Favorite Properties” list, the data is saved by these Session Cookies. So, the properties added to your list are not removed when you browse other pages." },
    { type: "h3", text: "2. Persistent Cookies" },
    { type: "p", text: "They are cookies that are stored and saved to remember visitors’ preferences until they are removed by the user. By remembering the users’ movements on the website and mobile page, they enable the user’s next experience to be customized." },
    { type: "p", text: "When you select “Remember me” while logging into your registered account at tekceexclusive.com, you will not need to enter your e-mail and password again, which is provided by persistent cookies." },
    { type: "h3", text: "3. Performance Cookies" },
    { type: "p", text: "Performance Cookies monitor the performance of the website, mobile page, or app. They do not collect any private data from the visitor. They just collect error messages and are used to perfect the website, mobile page, and app." },
    { type: "h3", text: "4. Functionality Cookies" },
    { type: "p", text: "They are used to remember user preferences of the mobile/website or app. Thanks to Functionality Cookies, notification preferences are remembered and the preference chosen by the visitor is applied without checking it again." },
    { type: "h3", text: "5. Google Analytics and Marketing Cookies" },
    { type: "p", text: "We use Google Analytics as described in “How Google uses data when you use our partners’ sites or apps?”. You can prevent your data from being used by Google Analytics on websites by installing the Google Analytics opt-out browser add-on here." },
    { type: "p", text: "We also use IP address masking. It is a technique used to truncate IP addresses collected by Google Analytics and store them in a shortened form to prevent them from being traced back to individual users." },
    { type: "p", text: "Portions of our website may use Google Analytics for Display Advertisers, including DoubleClick or Dynamic Remarketing, which provides interest-based ads based on your visit to this or other websites." },
    { type: "p", text: "You can use Ad Settings to manage the Google ads you see and opt out of interest-based ads. We also use Adobe Marketing Cloud as described here. You can opt out of the use of this information as described below." },
    { type: "h3", text: "6. Social Media Cookies" },
    { type: "p", text: "Social Media: Our websites include social media features, such as LinkedIn, Google, Facebook, and Twitter “share” buttons. These features may collect your IP address, which page you visit on our site, and may set a cookie to enable the feature to work properly." },
    { type: "p", text: "These services will also verify your identity and give you the option to share certain personal information with us, such as your name and email address, to pre-populate our registration form or provide feedback. Your interactions with these features are governed by the Privacy Policy of the company providing them." },
    { type: "p", text: "tekceexclusive.com provides service in 3 languages for now. When you select your preferred language, your preferences are remembered by these cookies. You will not have to choose the language again on your next visit." },
    { type: "h2", text: "How Does the Use of Cookies Help?" },
    { type: "p", text: "The aim of tekceexclusive.com in using cookies is to improve the experience visitors have on our website, mobile page, and application by making the portal more personal. The Use of Cookies provides us with sufficient data to remember the preferences of our visitors." },
    { type: "p", text: "The data is used to maintain functionality, provide visitors with a personalized portfolio and hot offers, to evaluate the ease of use and suitability of our website. In addition, cookies are used to provide you with relevant ads on websites." },
    { type: "h2", text: "The Security of the Data of Our Visitors" },
    { type: "p", text: "tekceexclusive.com saves and stores the data of our visitors in a very secure way within the framework of user permissions and legal regulations. We only connect our visitors to share properties and news that are absolutely useful to them." },
    { type: "p", text: "Contact information of our visitors, such as e-mail and phone number, is not and will not be shared with any other third-party company. The security and privacy of our visitors are guaranteed by our terms of use." },
    { type: "h2", text: "The Management of the Cookie Usage" },
    { type: "p", text: "Visitors can limit information sharing by navigating through their browser settings. In this case, the website, mobile page, or app may not work at full capacity. Visitors who limit the use of cookies are deemed to have accepted the performance problems related to cookies." },
    { type: "h2", text: "Categories of Cookies Used on the Platform" },
    { type: "p", lead: "Analytical Cookies:", text: "They allow us to recognize and count the number of visitors to our website, to see how visitors move around the website while using it, and to record what content viewers view and are interested in. It helps us to determine how often certain pages and ads are visited and the most popular areas of our website." },
    { type: "p", lead: "Technical Cookies:", text: "The technical cookies we use on our website are strictly linked to the performance of the website. These cookies detect non-working pages and areas of the platform." },
    { type: "p", lead: "Flash Cookies:", text: "A flash cookie, also known as a Local Shared Object or LSO, is a text file sent to a client by a Web server when the browser requests content supported by Adobe Flash, a popular browser plug-in. They are often used in website ads and videos." },
    { type: "p", lead: "Customization Cookies:", text: "They allow the user to specify or customize some aspects of the general options of the website, such as specifying the language, locale, or browser type." },
    { type: "h2", text: "Description and Duration of Cookies Used on the Platform" },
    { type: "h3", text: "Analytical Cookies" },
    { type: "p", lead: "Advertisement:", text: "It is used to show behavioral and target-oriented ads to visitors. The duration is 540 days from the initial setup of cookies or the last update. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Market Analysis:", text: "It is used to do market analysis. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Campaign/Promotional:", text: "It is used to calculate customer recycles and the effectiveness of campaigns. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Facebook:", text: "They allow Facebook members (or non-members) to be tracked for market analysis and product development. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Google Analytics:", text: "These cookies allow us to improve the presentation and use of the platform by collecting all statistical data. By collecting demographic statistics, Google analyzes user information, and it helps us better understand users." },
    { type: "p", text: "We use Google Analytics cookies on the platform. These cookies and the data collected are transferred to Google servers in the USA and are protected in accordance with Google’s Data Protection policies." },
    { type: "p", text: "You can click here to learn more about the principles of Google’s analytical data processing activities and the protection of personal data." },
    { type: "p", text: "The duration is 2 years from the initial setup of cookies or the last update." },
    { type: "p", lead: "Source Website:", text: "The source website is used to better understand users’ preferences and provide relevant content. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Last visit and movement:", text: "They are used to provide updates on what has changed since the last visit to the platform and to better understand users’ preferences. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "h3", text: "Technical Cookies" },
    { type: "p", lead: "Session:", text: "Session cookies are used to ensure the continuity of the session. The duration is 90 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "p", lead: "Load Balancing:", text: "They are used to reduce the server load by distributing the load. The duration is 30 minutes from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "h3", text: "Authentication Cookies" },
    { type: "p", lead: "User ID:", text: "They are used only for users to see their own information. The duration is 360 days from the initial setup or last update of the cookies. It is possible to accept or reject through the browser settings." },
    { type: "h2", text: "Can the Use of Cookies Be Blocked by Data Owners?" },
    { type: "p", text: "You can personalize your cookie preferences by changing your browser settings." },
    {
      type: "links",
      rows: [
        ["Adobe Analytics", "http://www.adobe.com/uk/privacy/opt-out.html"],
        ["AOL", "https://help.aol.com/articles/restore-security-settings-and-enable-cookie-settings-on-browser"],
        ["Google Adwords", "https://support.google.com/ads/answer/2662922?hl=en"],
        ["Google Analytics", "https://tools.google.com/dlpage/gaoptout"],
        ["Google Chrome", "https://www.google.com/support/chrome/bin/answer.py?hl=en&answer=95647"],
        ["Internet Explorer", "https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"],
        ["Mozilla Firefox", "http://support.mozilla.com/en-US/kb/Cookies"],
        ["Opera", "http://www.opera.com/browser/tutorials/security/privacy/"],
        ["Safari", "https://support.apple.com/kb/ph19214?locale=tr_TR"],
      ],
    },
  ],
};

export const LEGAL_NOTICES: LegalDocument = {
  slug: "legal",
  href: "/legal",
  title: "Legal Notices and Disclaimer",
  blocks: [
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is a registered brand. We are an overseas real estate company in Turkey. tekceexclusive.com is owned by Tekce Exclusive Gayrimenkul Pazarlama AŞ. You can find our legal notices and disclaimers on this page." },
    { type: "h2", text: "The Website Content of Tekce Exclusive Gayrimenkul Pazarlama AŞ" },
    { type: "p", text: "The content of tekceexclusive.com consists of the websites of the leading real estate agencies in Turkey and Spain: Antalya Homes ®, Istanbul Homes ®, Trabzon Homes ®, Bursa Homes ®, and Spain Homes ®." },
    { type: "p", text: "You can click and visit our websites to see real estate for sale, their details, prices, photos, real estate and testimonial videos, testimonial texts, articles, news, and blogs about buying real estate in Turkey and Spain." },
    { type: "h2", text: "Warnings to Website Users" },
    { type: "p", text: "Although the information published on our website has been prepared in good faith, there may be differences in the information given by the seller because of a change of opinion, spelling mistake, price update, or misinformation by third parties/institutions. The information published on our website is not a binding commitment to any contract." },
    {
      type: "ul",
      items: [
        "The announced real estate prices are the prices declared by the seller. These prices do not represent the actual selling price. The sellers are free to sell at the price they see appropriate. If there is no written agreement, the seller reserves the right to change prices without informing Tekce Exclusive Gayrimenkul Pazarlama AŞ.",
        "The real estate information entered in our real estate lists is not binding for any sales contract. Please confirm whether the information on our website is among the sales conditions of the property owner. Please get a written commitment from the property owner. We are not responsible if property owners do not keep their word.",
      ],
    },
    { type: "p", text: "If you believe that a property belonging to you on our websites is sold without your knowledge, please contact us via the contact form." },
    { type: "h2", text: "Legal Notice and Disclaimer" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ makes every effort to maintain the website properly and to ensure the accuracy and completeness of the information on this website. You should also be aware that the information on this website may become out of date over time." },
    { type: "p", text: "Although this information has been compiled with great care and is constantly updated, we take no responsibility for its accuracy, completeness, or up-to-date." },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ expressly reserves the right to change, delete or temporarily remove the content in whole or in part at any time without giving notice. Therefore, we are not responsible for any damage or loss caused related to the use of the generally published information, misuse, or technical errors." },
    { type: "h2", text: "Virus Disclaimer" },
    { type: "p", text: "We take all precautions to protect the website from viruses, but we do not warrant that any information, software, or other material accessible from the web pages is free of viruses, worms, Trojan horses, or other harmful components." },
    { type: "p", text: "We are not responsible and cannot be held responsible for any direct, indirect, incidental or consequential damages arising from the use, access, browsing or downloading of any information, data, text, pictures, or other materials accessible through Tekce Exclusive Gayrimenkul Pazarlama AŞ." },
    { type: "p", text: "You should take all appropriate precautions against viruses before accessing the website, its content, and the underlying software and/or related software." },
    { type: "h2", text: "Information About External Links" },
    { type: "p", text: "We log statistical information to refer to browsers, operating systems and security websites and to further improve our website. None of this information is distributed to third parties. All information collected from this website via e-mail will be kept strictly confidential and will not be sold or shared with any other party." },
    { type: "p", text: "But, our website contains links to websites owned and operated by third parties. If you use these links, you redirect to another website. These links are provided for information and convenience only. The responsibility of the linked websites lies solely with their operators." },
    { type: "p", text: "We have no control over the content of any linked website. We do not accept responsibility for any linked websites or their content. When you access an external website, you should be aware that Tekce Exclusive Gayrimenkul Pazarlama AŞ has no control over its content." },
    { type: "h2", text: "Copyright" },
    { type: "p", text: "tekceexclusive.com and all content, trademarks, services, logos, photos, designs, graphics, and software are protected, controlled, and/or licensed by Tekce Exclusive Gayrimenkul Pazarlama AŞ and/or its subsidiaries and affiliates." },
    { type: "strong", text: "The user is obliged to use the content of the website conscientiously, correctly, and in accordance with the law. You must also pay attention to these warnings;" },
    {
      type: "ul",
      items: [
        "It is prohibited to use the content or any part of the content on the website of Tekce Exclusive Gayrimenkul Pazarlama AŞ for any purpose.",
        "The use of our brand and other Tekce Exclusive Gayrimenkul Pazarlama AŞ logos or brands is strictly prohibited without our prior written consent.",
        "You may not copy, reproduce, republish, upload, post, transmit, or distribute any information or material from this website.",
        "You cannot distribute or commercially exploit the content without our express written permission. In addition, you cannot transmit or store the content on any other website or other forms of the electronic retrieval system.",
      ],
    },
    { type: "strong", text: "Any redistribution or reproduction of all or part of the content in any form is prohibited, except:" },
    {
      type: "ul",
      items: [
        "You can print or download them to local hard disk excerpts for your personal and non-commercial use only.",
        "You can copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material.",
      ],
    },
    { type: "p", text: "Our information on this website can be used, provided that you indicate the source of our information and refer to the following:" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ © 2018 – 2022 – All rights reserved. You must get permission from Tekce Exclusive Gayrimenkul Pazarlama AŞ for the use and reproduction of the content." },
    {
      type: "address",
      label: "The legal notice address of Tekce Exclusive Gayrimenkul Pazarlama AŞ for all languages;",
      lines: [
        "Legal notice address: Merdivenköy Mah. Nur Sok. Business Istanbul A Blok, No:1/A/410, 34732, Göztepe, Kadıköy",
        "İstanbul, Türkiye",
        "Phone: 0850 811 07 00",
        "E-mail: info@tekceexclusive.com",
      ],
    },
    { type: "p", text: "Notifications made to addresses other than this address are deemed not made." },
    { type: "p", text: "If you think there is content on our websites that bothers you, please contact us via our contact form or the information above." },
  ],
};

export const TERMS: LegalDocument = {
  slug: "terms",
  href: "/terms",
  title: "Terms of Website Use & Conditions",
  blocks: [
    { type: "p", text: "tekceexclusive.com is owned by Tekce Exclusive Gayrimenkul Pazarlama AŞ. We recommend that you read the terms and conditions of the website carefully before browsing. Your continued use of our website indicates that you accept and agree to our terms of use. If you do not accept the terms, you may avoid using our website." },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ fully abides by data security and storage by the Law on the Protection of Personal Data that entered into force on April 7, 2016." },
    { type: "h2", text: "Who Are We?" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ (“we” or “us” hereinafter) is the leading real estate company in Turkey. We are the sister company with the leading real estate brands in Turkey and Spain: Antalya Homes ®, Istanbul Homes ®, Trabzon Homes ®, Bursa Homes ®, and Spain Homes ®." },
    { type: "p", text: "We have offices in Lara (Antalya), Konyaaltı (Antalya), Alanya, Belek, Cevizlibağ (İstanbul Europe), Göztepe (İstanbul Asia), Bursa, Yalova, Trabzon, Ankara, Bodrum, and The Turkish Republic of Northern Cyprus." },
    { type: "p", text: "Our Nace code is 68.31.01, and the trade register number is 145567-5." },
    { type: "p", text: "Our company values are based on sustainability, excellence, innovation, integrity, and goodness. We never discriminate against people on the basis of gender, race, or skin color." },
    { type: "h2", text: "Changes to Our Terms and Website" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ can change or terminate the terms and websites at any time. You may check the terms to make sure you understand the current terms each time you wish to use our website." },
    { type: "h2", text: "The Purpose of Our Website" },
    { type: "p", text: "The purpose of the publications on our website in various languages and domains within Tekce Exclusive Gayrimenkul Pazarlama AŞ;" },
    {
      type: "ul",
      items: [
        "To introduce the services of “Tekce Exclusive Gayrimenkul Pazarlama AŞ” in various foreign languages",
        "To inform about the purchase of real estate in Turkey",
        "To list real estate advertisements",
      ],
    },
    { type: "h2", text: "We Use Cookies" },
    { type: "p", text: "Cookies are small text files placed on your computer while browsing the website. We use our own and third-party cookies to recognize you and your preferences, improve the performance of our website, and generate statistical data." },
    { type: "h2", text: "Why We Collect Your Data?" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ collects data to provide information and the best customer services to individuals, understand their needs and expectations, and in particular for the following reasons:" },
    {
      type: "ul",
      items: [
        "Personal and contact information such as name, surname, phone number, and e-mail address for better quality communication. We also use this information to send you hot offers in newsletter format via your e-mail address and to inform you about our new services.",
        "Demographic site or app browsing information to analyze and collect user points of interest. This data is used to improve business and operational activities such as marketing, retargeting, and communications.",
        "Social media information (Facebook, Twitter, Linkedin) to provide a better experience on the website. These social media can be only used to register on our website.",
        "Location information, such as IP address and current address, to suggest properties and show the closest offices by location.",
      ],
    },
    { type: "p", text: "We would like to see you as a member of our website when purchasing real estate from our company. We save your name, surname, telephone, and e-mail address that you have given us voluntarily." },
    { type: "p", text: "Only authorized persons (administration and real estate agents up to the sales stage and accountants in the post-sales stage) can see your data. We never use your data outside of the sale of a property. We will never share your data with a 3rd party company." },
    { type: "p", text: "Every time you call our company or our agents, you agree that we can call you back and send you mobile messages (SMS, Whatsapp, Viber, etc.). If you send an e-mail to our published mail address or fill out our web form, we assume that you agree that we can call you and send you information and newsletter e-mails regarding your inquiry." },
    { type: "h2", text: "We Respect Users’ Privacy" },
    { type: "p", text: "We take care of privacy in line with our corporate values. We only use 3rd party cookies to show customers what they are looking for. Only authorized personnel can view the e-mail, telephone, detailed identity information obtained during the contract, title deed after purchasing a property, tax number, and subscription documents." },
    { type: "p", text: "Your information will not be seen by anyone who is not authorized by the company. We use this data and documents only to serve you and for the purpose of selling a home. We can make phone calls, emails, and newsletters about properties you are interested in. We promise we do not bother you if you do not want to." },
    { type: "p", text: "You can read our Privacy Policy for detailed information on how we collect and use your personal information and protect your privacy." },
    { type: "h2", text: "Respect to Our Intellectual Property Rights" },
    { type: "p", text: "All content is our production and is created uniquely. We assume that you respect our intellectual property rights. Do not copy any content on our website." },
    { type: "p", text: "You can use our information content by linking to our website or by specifying the information source as “Tekce Exclusive Gayrimenkul Pazarlama AŞ”. We respect the Digital Millennium Copyright Act and defend our uniqueness with the DMCA." },
    { type: "h2", text: "Trademark Policy" },
    { type: "p", text: "Tekce Exclusive Gayrimenkul Pazarlama AŞ is our registered trademark. No one can use our logo and brand in the real estate sector." },
    { type: "h2", text: "Customer Feedback" },
    { type: "p", text: "We welcome your suggestions on how we can improve our service. If you have any questions, feedback, or complaints about these conditions or Tekce Exclusive Gayrimenkul Pazarlama AŞ, please use the contact details provided below." },
    {
      type: "address",
      label: "The legal notice address of Tekce Exclusive Gayrimenkul Pazarlama AŞ;",
      lines: [
        "Legal notice address: Merdivenköy Mah. Nur Sok. Business Istanbul A Blok, No:1/A/410, 34732, Göztepe, Kadıköy",
        "İstanbul, Türkiye",
        "Phone: 0850 811 07 00",
        "E-mail: info@tekceexclusive.com",
      ],
    },
  ],
};

/** In the order of the footer's legal links. */
export const LEGAL_DOCUMENTS = [PRIVACY, COOKIES, LEGAL_NOTICES, TERMS];
